CREATE TABLE operations_shipments (
    order_id BIGINT,
    order_date DATE,
    origin_port VARCHAR(20),
    carrier VARCHAR(20),
    tpt INT,
    service_level VARCHAR(10),
    ship_ahead_days INT,
    ship_late_days INT,
    customer VARCHAR(30),
    product_id INT,
    plant_code VARCHAR(20),
    destination_port VARCHAR(20),
    unit_quantity INT,
    weight DECIMAL(10,2),
    month VARCHAR(10),
    day_of_week VARCHAR(15),
    is_late INT,
    is_early INT,
    on_time INT,
    weight_per_unit DECIMAL(10,4),
    delay_severity VARCHAR(20),
    ai_efficiency_score DECIMAL(6,4),
    ai_recommendation VARCHAR(30)
);
